## NumPy vs Python list

In [1]:
import numpy as np

In [2]:
l = range(1000000)
l

range(0, 1000000)

In [3]:
m = np.arange(1000000)
m

array([     0,      1,      2, ..., 999997, 999998, 999999])

### we will check the time that in how much time the multiplication execute in list

In [4]:
%time for i in range(1, 10): r = [x*2 for x in l]

Wall time: 1.85 s


### now in NumPy array

In [5]:
%time for i in range(1,10): r=m*2

Wall time: 61 ms


## A Multidimensional Array Object

In [6]:
a = np.zeros((4,4))

In [7]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
b = np.ones((5,5))

In [9]:
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.empty((6,6)) # it may be empty

array([[3.76261741e-312, 3.76261635e-312, 0.00000000e+000,
        3.76289560e-312, 2.61054848e+106, 0.00000000e+000],
       [            nan, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 3.76264229e-312],
       [0.00000000e+000, 3.76267322e-312, 3.76267322e-312,
        3.76267322e-312, 3.76267322e-312, 3.76267322e-312],
       [8.91238232e-313, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [2.11377150e-314, 6.32404027e-322, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

### we can also convert a list to numpy array

In [11]:
L = [1,2,3,4]

In [12]:
c= np.array(L)

In [13]:
c

array([1, 2, 3, 4])

In [14]:
d = np.arange(1,100,10) # starting point, Ending point, spacer

In [15]:
d

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [16]:
e = [[1,2,3,4], [5,6,7,8]]

In [17]:
e = np.array(e)
e

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
e.ndim

2

In [19]:
e.dtype

dtype('int32')

### shape of the array

In [20]:
a.shape # two dimensional array

(4, 4)

In [21]:
b.shape # two dimensional array

(5, 5)

In [22]:
c.shape # one dimensional array

(4,)

In [23]:
d.shape

(10,)

### we can reshape any array to our desired array

In [24]:
e = a.reshape((2,2,2,2)) # four dimensional array

In [25]:
e

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

In [26]:
c.reshape((2,2)) # two dimensional array

array([[1, 2],
       [3, 4]])

In [27]:
d.reshape((2,5))

array([[ 1, 11, 21, 31, 41],
       [51, 61, 71, 81, 91]])

### we can check the dimentions of an array

In [28]:
a.ndim

2

In [29]:
b.ndim

2

In [30]:
c.ndim

1

In [31]:
d.ndim

1

In [32]:
e.ndim

4

### we can check the data type of array i.e float, integer, string

In [33]:
a.dtype

dtype('float64')

In [34]:
b.dtype

dtype('float64')

In [35]:
c.dtype

dtype('int32')

In [36]:
d.dtype

dtype('int32')

In [37]:
e.dtype

dtype('float64')

### different functions to create arrays

#### array

In [38]:
list1 = ["Hamza", "Talha", "Hasnain", "Shahwaiz", "Rafique"]

In [39]:
arr = np.array(list1)
arr

array(['Hamza', 'Talha', 'Hasnain', 'Shahwaiz', 'Rafique'], dtype='<U8')

#### asarray

In [40]:
arr2 = np.asarray(list1)
arr2

array(['Hamza', 'Talha', 'Hasnain', 'Shahwaiz', 'Rafique'], dtype='<U8')

#### arange

In [41]:
np.arange(1,100,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

#### ones

In [42]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### ones_like

In [43]:
np.ones_like(a)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### zeros

In [44]:
np.zeros((2,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

#### zeros_like

In [45]:
np.zeros_like(b)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### empty

In [46]:
np.empty((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### empty_like

In [47]:
np.empty_like(c)

array([16843009, 16843009, 16843009, 16843009])

#### full

In [48]:
np.full(10,10)

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

#### full_like

In [49]:
np.full_like(arr,64)

array(['64', '64', '64', '64', '64'], dtype='<U8')

#### eye

In [50]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### identity

In [51]:
np.identity(4, dtype = None)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Arithmetic with NumPy arrays

In [52]:
arr3 = np.array([[1,2,3,4],[5,6,7,8]])
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [53]:
arr3 * arr3

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [54]:
arr3/arr3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [55]:
arr3 * 9

array([[ 9, 18, 27, 36],
       [45, 54, 63, 72]])

In [56]:
arr3 - arr3

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [57]:
arr3 ** 2

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]], dtype=int32)

In [58]:
arr3 > 0

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [59]:
arr3[arr3 > 4]

array([5, 6, 7, 8])

## Indexing and slicing

#### one dimensional array

In [60]:
arr4 = np.array([1,2,3,4,5,6,7])
arr4

array([1, 2, 3, 4, 5, 6, 7])

In [61]:
arr4[3]

4

In [62]:
arr4[arr4 > 3]

array([4, 5, 6, 7])

In [63]:
arr4[[3,6]]

array([4, 7])

In [64]:
arr5 = np.arange(10)

In [65]:
arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
arr5[3:8]

array([3, 4, 5, 6, 7])

In [67]:
arr5[4:9]

array([4, 5, 6, 7, 8])

In [68]:
arr5[5]

5

In [69]:
arr5[0:3] = 1

In [70]:
arr5

array([1, 1, 1, 3, 4, 5, 6, 7, 8, 9])

#### two dimensional array

In [71]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
arr2d.ndim

2

In [73]:
arr2d[0]

array([1, 2, 3])

In [74]:
arr2d[1]

array([4, 5, 6])

In [75]:
arr2d[2]

array([7, 8, 9])

In [76]:
arr2d[0,2]

3

In [77]:
arr2d[1,1]

5

In [78]:
arr2d[2,0]

7

In [79]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [81]:
arr2d[:2, :1]

array([[1],
       [4]])

In [82]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [83]:
arr2d[1,:2]

array([4, 5])

In [84]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [85]:
arr2d[:2,1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

#### three dimensional array

In [86]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [87]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [88]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
arr3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [90]:
arr3d[1,0]

array([7, 8, 9])

In [91]:
arr3d[0,1]

array([4, 5, 6])

## Boolean Indexing 

In [92]:
names = np.array(["Husnain", "Hamza", "Husnain", "Hamza","Talha","Hamza","Talha"])
names

array(['Husnain', 'Hamza', 'Husnain', 'Hamza', 'Talha', 'Hamza', 'Talha'],
      dtype='<U7')

In [93]:
data = np.random.rand(7,4)

In [94]:
data

array([[0.79092004, 0.93207747, 0.5001849 , 0.42470288],
       [0.6132416 , 0.94915182, 0.54226504, 0.72647572],
       [0.086887  , 0.46088832, 0.64451842, 0.68846538],
       [0.50201314, 0.29601661, 0.67453843, 0.9094771 ],
       [0.74898814, 0.83066641, 0.79493951, 0.73147697],
       [0.39608636, 0.03981608, 0.90788998, 0.62145045],
       [0.20185926, 0.7822344 , 0.25784706, 0.55491853]])

In [95]:
data.ndim

2

In [96]:
names == "Husnain"

array([ True, False,  True, False, False, False, False])

In [97]:
data[names == "Husnain"]   # this will give the first row

array([[0.79092004, 0.93207747, 0.5001849 , 0.42470288],
       [0.086887  , 0.46088832, 0.64451842, 0.68846538]])

In [98]:
mask = (names == "Hamza") | (names == "Talha")

In [99]:
mask

array([False,  True, False,  True,  True,  True,  True])

In [100]:
data[mask]

array([[0.6132416 , 0.94915182, 0.54226504, 0.72647572],
       [0.50201314, 0.29601661, 0.67453843, 0.9094771 ],
       [0.74898814, 0.83066641, 0.79493951, 0.73147697],
       [0.39608636, 0.03981608, 0.90788998, 0.62145045],
       [0.20185926, 0.7822344 , 0.25784706, 0.55491853]])

In [101]:
data[data < 0 ] = 0

In [102]:
data

array([[0.79092004, 0.93207747, 0.5001849 , 0.42470288],
       [0.6132416 , 0.94915182, 0.54226504, 0.72647572],
       [0.086887  , 0.46088832, 0.64451842, 0.68846538],
       [0.50201314, 0.29601661, 0.67453843, 0.9094771 ],
       [0.74898814, 0.83066641, 0.79493951, 0.73147697],
       [0.39608636, 0.03981608, 0.90788998, 0.62145045],
       [0.20185926, 0.7822344 , 0.25784706, 0.55491853]])

In [103]:
 data[data > 0] = 0

In [104]:
data

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [105]:
data[names != "Hamza"] = 313

In [106]:
data

array([[313., 313., 313., 313.],
       [  0.,   0.,   0.,   0.],
       [313., 313., 313., 313.],
       [  0.,   0.,   0.,   0.],
       [313., 313., 313., 313.],
       [  0.,   0.,   0.,   0.],
       [313., 313., 313., 313.]])

## Fancy Indexing

In [107]:
arr6 = np.empty((8,4))

In [108]:
arr6

array([[3.76338584e-312, 3.76338584e-312, 3.76338584e-312,
        3.76338584e-312],
       [3.76338584e-312, 3.76338584e-312, 3.76338584e-312,
        3.76338584e-312],
       [3.76338584e-312, 3.76338584e-312, 3.76338584e-312,
        3.76338584e-312],
       [3.76338584e-312, 3.76338584e-312, 3.76338584e-312,
        3.76338584e-312],
       [3.76338584e-312, 3.76338584e-312, 3.76338584e-312,
        3.76338584e-312],
       [3.76338584e-312, 3.76338584e-312, 3.76338584e-312,
        3.76338584e-312],
       [3.76338584e-312, 3.76338584e-312, 3.76338584e-312,
        3.76338584e-312],
       [3.76338584e-312, 3.76338584e-312, 3.76338584e-312,
        3.76338584e-312]])

In [109]:
for i in range(8):
    arr6[i] = i

In [110]:
arr6

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [111]:
arr6[[0,1,2,3]]

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [112]:
arr6[[4,5,6,7]]

array([[4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [113]:
arr6[[-8,-5,-2]]

array([[0., 0., 0., 0.],
       [3., 3., 3., 3.],
       [6., 6., 6., 6.]])

## Transposing Arrays and Swapping Axes

In [114]:
arr7 = np.arange(15).reshape((3,5))

In [115]:
arr7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [116]:
arr7.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [117]:
np.dot(arr7, arr7.T)

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [118]:
arr8 = np.arange(16).reshape((2,2,4))

In [119]:
arr8

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [120]:
arr8.ndim

3

In [121]:
arr8.T

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [122]:
arr8.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

## Fast Element-Wise Array Function

In [123]:
arr9 = np.array([10,49,36,65,81,121])

In [124]:
arr9

array([ 10,  49,  36,  65,  81, 121])

In [125]:
np.sqrt(arr9)

array([ 3.16227766,  7.        ,  6.        ,  8.06225775,  9.        ,
       11.        ])

In [126]:
np.power(arr9, 2)

array([  100,  2401,  1296,  4225,  6561, 14641], dtype=int32)

In [127]:
arr10 = np.array([21,4,65,56,34,87])
arr10

array([21,  4, 65, 56, 34, 87])

In [128]:
np.maximum(arr9, arr10)

array([ 21,  49,  65,  65,  81, 121])

In [129]:
np.exp(arr9)

array([2.20264658e+04, 1.90734657e+21, 4.31123155e+15, 1.69488924e+28,
       1.50609731e+35, 3.54513118e+52])

In [130]:
arr11 = np.random.rand(5)*5

In [131]:
arr11

array([3.21801358, 3.43863842, 3.2387422 , 3.13757379, 0.2924561 ])

In [132]:
remainder, whole_part = np.modf(arr11)

In [133]:
remainder

array([0.21801358, 0.43863842, 0.2387422 , 0.13757379, 0.2924561 ])

In [134]:
whole_part

array([3., 3., 3., 3., 0.])

In [135]:
np.square(arr3)

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]], dtype=int32)

In [136]:
np.exp(arr3)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03]])

In [137]:
np.log10(arr3)

array([[0.        , 0.30103   , 0.47712125, 0.60205999],
       [0.69897   , 0.77815125, 0.84509804, 0.90308999]])

In [138]:
np.log2(arr3)

array([[0.        , 1.        , 1.5849625 , 2.        ],
       [2.32192809, 2.5849625 , 2.80735492, 3.        ]])

In [139]:
np.sign(arr6)   # 1 = positive   0 = zero  -1 = negative

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [140]:
np.ceil(arr5)

array([1., 1., 1., 3., 4., 5., 6., 7., 8., 9.])

In [141]:
np.floor(arr8)

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]],

       [[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]])

## Expressing Conditional Logics as Array Operations 

### A vectorized version of ternary operation x if condition else y

In [142]:
salary = np.array([65000, 50000, 120000, 0, -5, 75000])

In [143]:
np.where(salary <= 0, 25000, salary)

array([ 65000,  50000, 120000,  25000,  25000,  75000])

In [144]:
np.where(salary <= 0, "Not OK", "OK")

array(['OK', 'OK', 'OK', 'Not OK', 'Not OK', 'OK'], dtype='<U6')

In [145]:
arr12 = np.array([1.1,1.2,1.3,1.4,1.5])

In [146]:
arr13 = np.array([2.1,2.2,2.3,2.4,2.5])

In [147]:
cond = np.array([True, False, True, False, True])

In [148]:
result = np.where(cond, arr12, arr13)

In [149]:
result

array([1.1, 2.2, 1.3, 2.4, 1.5])

In [150]:
arr14 = np.random.rand(4,4)

In [151]:
arr14

array([[0.12694375, 0.48552042, 0.25393466, 0.09365154],
       [0.18843436, 0.0112607 , 0.03094047, 0.99152431],
       [0.42538167, 0.41071076, 0.4099883 , 0.69838542],
       [0.61866199, 0.61072574, 0.97500721, 0.62346304]])

In [152]:
arr14 > 0

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [153]:
np.where(arr14 > 0, "Positive", "Negative" )

array([['Positive', 'Positive', 'Positive', 'Positive'],
       ['Positive', 'Positive', 'Positive', 'Positive'],
       ['Positive', 'Positive', 'Positive', 'Positive'],
       ['Positive', 'Positive', 'Positive', 'Positive']], dtype='<U8')

In [154]:
np.where(arr14 > 0, 2, arr14)

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

## Mathematical and Statistical

In [155]:
np.mean(arr9)

60.333333333333336

In [156]:
np.mean(arr12)

1.3

In [157]:
np.cumsum(arr9)

array([ 10,  59,  95, 160, 241, 362], dtype=int32)

In [158]:
np.cumsum(arr12)

array([1.1, 2.3, 3.6, 5. , 6.5])

In [159]:
np.cumproduct(arr9)

array([         10,         490,       17640,     1146600,    92874600,
       -1647075288], dtype=int32)

In [160]:
np.cumprod(arr9)

array([         10,         490,       17640,     1146600,    92874600,
       -1647075288], dtype=int32)

In [161]:
np.cumproduct(arr12)

array([1.1   , 1.32  , 1.716 , 2.4024, 3.6036])

In [162]:
y = arr9 >10

In [163]:
y

array([False,  True,  True,  True,  True,  True])

In [164]:
y.sum()

5

In [165]:
y.any()

True

In [166]:
y.all()

False

In [167]:
arr9.sort()


In [168]:
arr9

array([ 10,  36,  49,  65,  81, 121])

In [169]:
np.unique(arr9)

array([ 10,  36,  49,  65,  81, 121])

In [170]:
np.unique(names)

array(['Hamza', 'Husnain', 'Talha'], dtype='<U7')

## File input output with Arrays

In [171]:
arr14 = np.arange(10)

In [172]:
np.save('some_array', arr14)

In [173]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Linear Algebra

### Dot product

In [174]:
arr15 = np.array([[1,2,3], [4,5,6]])

In [175]:
arr15

array([[1, 2, 3],
       [4, 5, 6]])

In [179]:
arr16 = np.array([[7,8],[9,10],[11,12]])

In [180]:
arr16

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [181]:
np.dot(arr15, arr16)

array([[ 58,  64],
       [139, 154]])

In [182]:
arr15.dot((np.ones(3)))

array([ 6., 15.])

In [188]:
arr16 = np.arange(16).reshape(4,4)

In [189]:
arr16

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## Pseudorandom Number Generation

In [192]:
arr17 = np.random.normal(size = (4,4))

In [193]:
arr17

array([[ 0.63937899, -0.18690501, -0.55066873, -1.35567243],
       [ 0.04744534,  0.0166083 , -0.71878417, -0.02096568],
       [ 0.20208891,  0.14381636, -0.49936269, -0.09714663],
       [ 1.05703059, -0.62152159, -0.44294838,  0.88447146]])

In [196]:
arr18 = np.random.uniform(size =(4,4))

In [197]:
arr18

array([[0.07630829, 0.77991879, 0.43840923, 0.72346518],
       [0.97798951, 0.53849587, 0.50112046, 0.07205113],
       [0.26843898, 0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 , 0.90959353]])

In [200]:
arr19 = np.random.seed(a)

TypeError: Cannot cast array data from dtype('float64') to dtype('int64') according to the rule 'safe'

## Reshaping

In [201]:
arr20 = np.arange(8)

In [202]:
arr20

array([0, 1, 2, 3, 4, 5, 6, 7])

In [203]:
arr20.reshape((2,4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [204]:
arr20.reshape((4,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [205]:
arr20.reshape((4,2), order = "C")

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [206]:
arr20.reshape((4,2), order = "F")

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [207]:
arr21 = np.arange(15)

In [208]:
arr21

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [209]:
arr21.reshape((5, -1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [210]:
arr21.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [211]:
arr20.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

## Concatenatenation

In [213]:
arr22 = np.array([[1,3,5],[7,9,11]])

In [214]:
arr23 = np.array([[13,15,17],[19,21,23]])

In [215]:
np.concatenate((arr22,arr23), axis=0)

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23]])

In [216]:
np.concatenate((arr22,arr23),axis=1)

array([[ 1,  3,  5, 13, 15, 17],
       [ 7,  9, 11, 19, 21, 23]])

In [217]:
np.vstack((arr22,arr23))

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23]])

In [218]:
np.hstack((arr22, arr23))

array([[ 1,  3,  5, 13, 15, 17],
       [ 7,  9, 11, 19, 21, 23]])

## Split

In [219]:
arr21

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [220]:
np.split(arr21,[4,9])

[array([0, 1, 2, 3]), array([4, 5, 6, 7, 8]), array([ 9, 10, 11, 12, 13, 14])]

In [221]:
arr23

array([[13, 15, 17],
       [19, 21, 23]])

In [222]:
np.split(arr23,[2,4])

[array([[13, 15, 17],
        [19, 21, 23]]),
 array([], shape=(0, 3), dtype=int32),
 array([], shape=(0, 3), dtype=int32)]

In [226]:
np.split(arr23,[2,3],axis=1)

[array([[13, 15],
        [19, 21]]),
 array([[17],
        [23]]),
 array([], shape=(2, 0), dtype=int32)]

## tile and repeat

In [227]:
np.repeat(arr21,2)

array([ 0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,
        8,  9,  9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14])

In [228]:
np.tile(arr21,2)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,  0,  1,
        2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])